---
network:
    version: 2
    renderer: networkd
    wifis:
        wlan0:
            dhcp4: true
            access-points:
                "Kokosbusserl":
                    password: "ichessegerne13bananen!"
